### ISSUE TITLE
hpprint todo

### ISSUE THREAD

**Issue by haxscramper** [haxscramper/hmisc#6]
- [ ] runtime switching for `pairs`/`items` use for objects
- [ ] rewrite `treeRepr` from hpprint_repr
- [ ] Add lisp repr
- [ ] show `<nil>` types in all representations. Introduce procedures for default formatting of primitive ptrees - 'visited',  'nil', 'ignored' and 'const'.
- [ ] Reuse formatting options from clformat - global configuration  for primitive type formatting
- [ ] Allow multicolored constants - use `ColoredText` instead of simple string. Do formatting in-place instead of lyt block conversion stage, this is the only way to get access to the important data.
- [ ] Store pretty-printed tree in JSON from and read it back again. Can reuse jsony this.
- [ ] Implement tree diffing - take to trees and produce new one with all elements annotated. Partially implemented, but needs more edge cases, also tests this with trees that were read from serialized form.
- [ ] Generate exact tree repr from variant objects - use `.kind`, `items`. Pass `static[seq[string]]` list of fields that have to be ignored, add all others as well. Paired with `treeDiff` can be used to spot mismatches in the generated AST.
